In [0]:
import pandas as pd 
# Making data frame from the csv file 
df1 = pd.read_csv("out.csv")#dataset loding



**Libreary function adding**

In [0]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
from pylab import rcParams
import sklearn
import urllib
from sklearn.neighbors import KNeighborsRegressor
from sklearn import neighbors
from sklearn import preprocessing
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

**Show Nan**

In [0]:
df1[:10]

chromosome number  ...  fraction of reads have dna methylation
0                 15  ...                                     NaN
1                 15  ...                                0.416667
2                 15  ...                                0.914286
3                 15  ...                                0.670732
4                 15  ...                                0.978495
5                 15  ...                                0.756522
6                 15  ...                                0.877863
7                 15  ...                                0.889796
8                 15  ...                                0.545817
9                 15  ...                                0.937008

[10 rows x 6 columns]

**Dataset processing , Empty value replace with ) BZ empty value/Nan can not read**

In [0]:
df = df1.replace(np.nan, 0, regex=True)

In [0]:
df[:10] 

chromosome number  ...  fraction of reads have dna methylation
0                 15  ...                                0.000000
1                 15  ...                                0.416667
2                 15  ...                                0.914286
3                 15  ...                                0.670732
4                 15  ...                                0.978495
5                 15  ...                                0.756522
6                 15  ...                                0.877863
7                 15  ...                                0.889796
8                 15  ...                                0.545817
9                 15  ...                                0.937008

[10 rows x 6 columns]



**To Determine the Formate the way floating numbrs are dysplayed, Precision number of digits for floating output, suppress if true precision will work**

In [0]:
np.set_printoptions(precision=4,suppress=True)
%matplotlib inline
rcParams['figure.figsize']=7,4 #to resize the figure 
plt.style.use('seaborn-whitegrid')

**Features extraction**
**Dependent 5 no Column**
**Independet 1,2 column**

In [0]:
X_prime = df.iloc[:,[1,2]].values
y = df.iloc[:,5].values
# y=y.astype(float)
#X=preprocessing.scale(X_prime)



**Convert array to list bz we need comma separate valeu & list advantage**

In [0]:
# print(type(X_prime))
# X_prime = X_prime.tolist()
# y = y.tolist()

**Devided train and test dataset.....33% test**

In [0]:
train, validate, test = np.split(df.sample(frac=1), [int(.6*len(df)), int(.8*len(df))])
# X_train,X_test,y_train,y_test=train_test_split(X_prime,y,test_size=.33,random_state=17)
# kfold = sklearn.model_selection.KFold(n_splits=10, random_state=0, shuffle=True)
# cv_results = sklearn.model_selection.cross_val_score(clf, X, Y, cv=kfold, scoring='accuracy')

In [0]:
***model.fit(train_images, train_labels, validation_data=(val_images, val_labels), epochs=15, batch_size=500, callbacks=callbacks_list)
    scores = model.evaluate(val_images, val_labels, verbose=0)
    print("CNN Error: %.2f%%" % (100-scores[1]*100))***

SyntaxError: ignored

**Model Buildup**
**Fit**

In [0]:
clf=neighbors.KNeighborsRegressor(n_neighbors=2)
clf.fit(X_train,y_train)
cv_results = sklearn.model_selection.cross_val_score(clf, X_test, cv=kfold, scoring='accuracy')

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
TypeError: fit() missing 1 required positional argument: 'y'

  FitFailedWarning)


In [0]:
print(type(X_test))
print(X_test[0])

<class 'numpy.ndarray'>
[19267093 19267095]


In [0]:
X_test

array([[19267093, 19267095],
       [19715671, 19715673],
       [18229147, 18229149],
       ...,
       [18948893, 18948895],
       [18458209, 18458211],
       [17490081, 17490083]])

In [0]:
#y_expect=y_test
y_pred=clf.predict([[17000043,17000045]])
y_pred

array([0.7925])

In [0]:
#y_expect=y_test
y_pred=clf.predict([[17000186,17000188]])
y_pred

array([0.7925])

In [0]:
#y_expect=y_test
y_pred=clf.predict([[17007123,17000125]])
y_pred


array([0.])

In [0]:
#y_expect=y_test
y_pred=clf.predict([[17008882,17008884]])
y_pred


array([0.3012])

In [0]:
y_pred1=clf.predict(X_test)

In [0]:
print(y_pred1)

[0.     0.     0.     ... 0.     0.4301 0.    ]


In [0]:
print(y_pred)

[0.2083]
